return {
  "Floppa",
  "Golden Floppa",
  "Doge",
  "Cheems",
  "Staring Fish",
  "Hamster",
  "The Rock",
  "Banana Cat",
  "Egg Dog",
  "Popcat",
  "Smiling Cat",
  "Killerfish",
  "Bingus",
  "Floppy",
  "Creepy Head",
  "Scary Skull",
  "Troll Face",
  "Uncanny Cat",
  "Quandale Dingle",
  "Red Sus",
  "Sus Duck",
  "Sigma Man",
  "Dancing Cat",
  "Toothless Dragon",
  "Manly Nugget",
  "Huh Cat",
  "Mystical Tree",
  "Old Man",
  "Nyan Cat",
  "Baller",
  "Slicer",
  "Rick Roller",
  "Gigachad",
  "MrBeast",
  "Handsome Man"
}